// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoticiasWebAPI;

namespace NoticiasWebAPI.Migrations
{
    [DbContext(typeof(NoticiasDBContext))]
    [Migration("20190504181005_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoticiasWebAPI.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("APELLIDO")
                        .HasMaxLength(100);

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE")
                        .HasMaxLength(50);

                    b.HasKey("AutorID");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("NoticiasWebAPI.Models.Noticia", b =>
                {
                    b.Property<int>("NoticiaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorID")
                        .HasColumnName("AUTOR_ID")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .HasColumnName("CONTENIDO")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPCIÓN")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("FECHA")
                        .HasColumnType("Datetime");

                    b.Property<string>("Titulo")
                        .HasColumnName("TITULO")
                        .HasMaxLength(50);

                    b.HasKey("NoticiaID");

                    b.HasIndex("AutorID");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("NoticiasWebAPI.Models.Noticia", b =>
                {
                    b.HasOne("NoticiasWebAPI.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
